import type { VerificationReport } from './types.js';

const baseTimestamp = '2026-05-23T19:42:11Z';

export const sampleReport: Record<string, VerificationReport> = {
  mostly_true: {
    claim: 'Iceland runs on nearly 100% renewable electricity, mainly hydro and geothermal.',
    verdict: 'mostly_true',
    confidence: 0.9,
    oneLiner: 'Iceland generates ~99.98% of its electricity from hydro and geothermal, but total energy still includes some oil imports.',
    context:
      'Iceland\'s electricity grid is effectively 100% renewable: roughly 70% hydro and 30% geothermal per the National Energy Authority. Total primary energy supply is also dominated by renewables (~85%) but transport and fishing fleets still rely on imported petroleum.',
    sources: [
      {
        title: 'Energy statistics 2024',
        url: 'https://orkustofnun.is/utgafa/skyrslur/orkutolur',
        publisher: 'Orkustofnun (National Energy Authority of Iceland)',
        stance: 'supports',
        weight: 92,
        excerpt: '99.98% of electricity generated in Iceland in 2024 came from renewable sources, split between hydro and geothermal.',
      },
      {
        title: 'Country profile: Iceland',
        url: 'https://www.iea.org/countries/iceland',
        publisher: 'International Energy Agency',
        stance: 'supports',
        weight: 88,
        excerpt: 'Iceland\'s electricity is almost entirely renewable. Fossil fuels still account for transport and parts of industry.',
      },
      {
        title: 'Iceland: 100% renewable electricity but oil-heavy transport',
        url: 'https://www.reuters.com/business/energy/iceland-renewable-2024-08-12/',
        publisher: 'Reuters',
        stance: 'contextual',
        weight: 74,
        excerpt: 'Transport fuel imports keep Iceland\'s overall energy mix below the "fully renewable" line some claims suggest.',
      },
      {
        title: 'Renewables in the Nordics',
        url: 'https://www.nordicstatistics.org/energy/renewables',
        publisher: 'Nordic Statistics',
        stance: 'supports',
        weight: 81,
        excerpt: 'Iceland leads the Nordics on renewable share of electricity production at ~100%.',
      },
      {
        title: 'Geothermal at full tilt: how Iceland built its grid',
        url: 'https://www.economist.com/europe/2025/02/01/iceland-energy',
        publisher: 'The Economist',
        stance: 'supports',
        weight: 70,
        excerpt: 'Hydro and geothermal together cover Icelandic power demand year round, with surplus exported as aluminium smelting.',
      },
    ],
    supportPct: 78,
    refutePct: 4,
    contextPct: 18,
    sourceWeights: [92, 88, 74, 81, 70],
    recencyTrend: [22, 28, 35, 30, 42, 55, 70, 88],
    generatedAt: baseTimestamp,
    model: 'claude-opus-4-7',
    latencyMs: 5840,
  },
  false: {
    claim: 'The Great Wall of China is visible from the Moon with the naked eye.',
    verdict: 'false',
    confidence: 0.97,
    oneLiner: 'NASA and astronauts agree: the Great Wall is not visible from the Moon, and barely visible from low Earth orbit.',
    context:
      'The Wall averages roughly 6 metres wide. At the Moon\'s distance (~384,000 km) this is far below the angular resolution of the human eye. Even from the ISS at ~400 km altitude, astronauts including Chris Hadfield report the Wall is hard to see without optical aid. NASA has debunked this myth on multiple occasions.',
    sources: [
      {
        title: 'China\'s Wall less great in view from space',
        url: 'https://www.nasa.gov/vision/space/workinginspace/great_wall.html',
        publisher: 'NASA',
        stance: 'refutes',
        weight: 95,
        excerpt: 'Despite a popular belief, the Great Wall of China cannot be seen from the Moon. It is also barely visible from low Earth orbit.',
      },
      {
        title: 'Can you see the Great Wall from space?',
        url: 'https://www.scientificamerican.com/article/great-wall-from-space/',
        publisher: 'Scientific American',
        stance: 'refutes',
        weight: 88,
        excerpt: 'Optical physics rules it out: the Wall\'s width is below the human eye\'s resolution limit at orbital altitudes, never mind lunar distance.',
      },
      {
        title: 'Chris Hadfield: the Great Wall is one of the hardest things to spot from orbit',
        url: 'https://www.bbc.com/news/science-2024-hadfield-great-wall',
        publisher: 'BBC',
        stance: 'refutes',
        weight: 82,
        excerpt: '"You can see roads and rivers easily. The Wall? Almost impossible without a long lens," Hadfield told the BBC.',
      },
      {
        title: 'The persistent myth of seeing the Great Wall from the Moon',
        url: 'https://www.snopes.com/fact-check/great-wall-of-china-from-moon/',
        publisher: 'Snopes',
        stance: 'refutes',
        weight: 70,
        excerpt: 'The claim is repeated in textbooks and tour guides but has been debunked by every astronaut who has been asked.',
      },
    ],
    supportPct: 2,
    refutePct: 92,
    contextPct: 6,
    sourceWeights: [95, 88, 82, 70],
    recencyTrend: [80, 65, 60, 55, 50, 48, 45, 40],
    generatedAt: baseTimestamp,
    model: 'claude-opus-4-7',
    latencyMs: 5120,
  },
  misleading: {
    claim: '5G networks cause increased rates of cancer in users.',
    verdict: 'misleading',
    confidence: 0.94,
    oneLiner: 'No peer-reviewed study has linked 5G exposure to cancer. The frequencies used remain non-ionizing and below WHO safety limits.',
    context:
      'The WHO, FCC, and ICNIRP have all reviewed 5G frequencies and find no evidence of carcinogenic effect at exposure levels seen in commercial deployments. The radiation is non-ionizing and cannot break chemical bonds the way UV or X-rays do. Cancer rates in 5G-rollout regions track underlying demographics, not network coverage.',
    sources: [
      {
        title: 'Radiation: 5G mobile networks and health',
        url: 'https://www.who.int/news-room/questions-and-answers/item/radiation-5g-mobile-networks-and-health',
        publisher: 'World Health Organization',
        stance: 'refutes',
        weight: 96,
        excerpt: 'Exposure from 5G networks is below international safety limits. No adverse health effects have been causally linked to wireless technologies.',
      },
      {
        title: 'ICNIRP guidelines for limiting exposure',
        url: 'https://www.icnirp.org/en/publications/article/rf-guidelines-2020.html',
        publisher: 'ICNIRP',
        stance: 'refutes',
        weight: 90,
        excerpt: 'New 2020 guidelines confirm 5G frequencies fall within reviewed safety thresholds.',
      },
      {
        title: 'Cancer incidence and mobile phone use: large cohort review',
        url: 'https://www.nejm.org/doi/10.1056/NEJMra2300148',
        publisher: 'New England Journal of Medicine',
        stance: 'refutes',
        weight: 88,
        excerpt: 'Pooled 2 million-participant cohorts show no statistically significant rise in brain tumour incidence attributable to mobile networks.',
      },
      {
        title: 'How the 5G health rumour spread on WhatsApp',
        url: 'https://www.theguardian.com/technology/2024/03/5g-conspiracy',
        publisher: 'The Guardian',
        stance: 'contextual',
        weight: 65,
        excerpt: 'Traces the origin of the cancer claim to a single misinterpreted 2018 NTP rat study using 2G frequencies, not 5G.',
      },
    ],
    supportPct: 5,
    refutePct: 85,
    contextPct: 10,
    sourceWeights: [96, 90, 88, 65],
    recencyTrend: [40, 55, 70, 75, 60, 55, 50, 45],
    generatedAt: baseTimestamp,
    model: 'claude-opus-4-7',
    latencyMs: 6210,
  },
};
